Repository grafana/terraform-provider-grafana, pull requests merged in 2020-10, with the labels that each got.

#114 Settings is an argument not a block
  website/docs/r/alert_notification.html.md
Labels: documentation, size/XS

#123 Automated Releases
  .github/workflows/release.yml
  .goreleaser.yml
Labels: enhancement

#125 grafana_user is importable
  grafana/resource_user.go
  website/docs/r/user.html.md
Labels: enhancement

#126 Examples are formatted properly
  website/docs/r/alert_notification.html.md
  website/docs/r/dashboard.html.md
  website/docs/r/organization.html.md
Labels: documentation

#127 Targets/Docs for Releases and Changelog Generation
  GNUmakefile
  README.md
Labels: enhancement

#116 Change user lists to sets
  grafana/resource_organization.go
  grafana/resource_organization_test.go
  website/docs/r/organization.html.md
Labels: size/XS
