Repository grafana/terraform-provider-grafana, pull requests merged in 2020-06, with the labels that each got.

#94 Allow alert notification reminder to be turned on
  grafana/resource_alert_notification.go
  grafana/resource_alert_notification_test.go
  website/docs/r/alert_notification.html.md
Labels: documentation, size/M

#93 Updating the access_mode setting description.
  website/docs/r/data_source.html.md
Labels: documentation, size/XS

#90 Update resource grafana_data_source
  go.mod
  go.sum
  grafana/resource_data_source.go
  grafana/resource_data_source_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/nytm/go-grafana-api/client.go
  vendor/github.com/nytm/go-grafana-api/dashboard.go
  vendor/github.com/nytm/go-grafana-api/datasource.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/data_source.html.md
Labels: dependencies, size/XXL

#87 Add uid value to alert notification resource
  go.mod
  go.sum
  grafana/resource_alert_notification.go
Labels: enhancement, size/XS

#98 Fix build, use -mod=readonly
  .go-version
  .travis.yml
  go.mod
Labels: size/XS

#99 Update link to documentation
  website/docs/r/alert_notification.html.md
Labels: documentation, size/XS

#100 resource/data_source: add support for stackdriver privatekey
  grafana/resource_data_source.go
  grafana/resource_data_source_test.go
  website/docs/r/data_source.html.md
Labels: documentation, enhancement, size/S
